### ISSUE TITLE
Bodenstationsoftware Missionplaner unter Linux zum laufen bringen -> Wiki

### ISSUE THREAD

**Issue by Residuum0** [Tri-o-copter/Brainware#3]

**Comment by x-sven** [comment]
... oder Cross Compiler unter Windows!?

**Comment by x-sven** [comment]
Hmm, gebe erst mal wegen vorliegender linkerfehler auf :-/

**Comment by Residuum0** [comment]
Am besten wohl unter Linux direkt.

Am 24.06.2015 um 22:04 schrieb x-sven:

**Comment by x-sven** [comment]
Ja, aber da fehlt ja die gcs. Dieser permanente Wechsel ist nervig. Geht eigentlich nur mit einer VM. Die muss ich morgen erst mal mitbringen :-)

**Comment by x-sven** [comment]
Oder meinst Du nativ auf'n Pi!?

**Comment by Residuum0** [comment]
Wollten wir die GCS (Missionplaner o.Ä.) nicht unter Mint zum laufen 
bringen? Dann gibt es doch keinen Wechsel mehr?

Am 24.06.2015 um 22:10 schrieb x-sven:

**Comment by x-sven** [comment]
Eigentlich wollte ich eher die brainware unter windows kompilieren. Ich 
bin skeptisch, ob das mit dem APM Missionplanner unter Linux geht und 
nicht nach jedem Update wieder ein neuer Krampf wird. Würde aber mal 
Sinn machen. Eine gute Anleitung habe ich aber noch nicht entdeckt...

Am 24.06.2015 um 22:12 schrieb Residuum0:

**Comment by x-sven** [comment]
http://meiboom.de/doku.php?id=tricopter:gcs

(könnte mal jemand richtig formatieren...)

**Comment by Residuum0** [comment]
Am 25.06.2015 um 07:57 schrieb x-sven:
> http://meiboom.de/doku.php?id=tricopter:gcs
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Tri-o-copter/Brainware/issues/3#issuecomment-115116012
Wann wolltest du los legen und wie?

**Comment by x-sven** [comment]
Stichwort Windows: Missionplanner
Stichwort Linux: APM Planner
...fertig ;-)
